image: ubuntu:latest

teams:
  stage: deploy
  script:
    - |
      apt-get update && apt-get install -y ca-certificates && apt-get install -y wget && apt-get install -y curl
      
      update-ca-certificates 
      wget -q https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64.tar.gz -O - |\
        tar xz && mv yq_linux_amd64 /usr/bin/yq

      files="./teams/*.yml"
      for f in $files
      do
        id=$(yq .id $f)
        json=$(yq -o json $f)
        curl -X 'PUT' \
          "https://app.datamesh-manager.com/api/teams/$id" \
          -H "accept: */*" \
          -H "x-api-key: $GITOPS_EXAMPLE_API_KEY" \
          -H "Content-Type: application/json" \
          -d "$json" \
          -f
      done

source-systems:
  stage: deploy
  needs: [teams]
  script:
    - |
      apt-get update && apt-get install -y ca-certificates && apt-get install -y wget && apt-get install -y curl
      
      update-ca-certificates 
      wget -q https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64.tar.gz -O - |\
        tar xz && mv yq_linux_amd64 /usr/bin/yq
      
      files="./sourcesystems/*.yml"
      for f in $files
      do
        id=$(yq .id $f)
        json=$(yq -o json $f)
        curl -X 'PUT' \
          "https://app.datamesh-manager.com/api/sourcesystems/$id" \
          -H "accept: */*" \
          -H "x-api-key: $GITOPS_EXAMPLE_API_KEY" \
          -H "Content-Type: application/json" \
          -d "$json" \
          -f
      done

data-products:
  stage: deploy
  needs: [source-systems]
  script:
    - |
      apt-get update && apt-get install -y ca-certificates && apt-get install -y wget && apt-get install -y curl
      
      update-ca-certificates 
      wget -q https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64.tar.gz -O - |\
        tar xz && mv yq_linux_amd64 /usr/bin/yq
      
      files="./dataproducts/*.yml"
      for f in $files
      do
        id=$(yq .info.id $f)
        json=$(yq -o json $f)
        curl -X 'PUT' \
          "https://app.datamesh-manager.com/api/dataproducts/$id" \
          -H "accept: */*" \
          -H "x-api-key: $GITOPS_EXAMPLE_API_KEY" \
          -H "Content-Type: application/json" \
          -d "$json" \
          -f
      done
